### ISSUE TITLE
Switch to collection helpers

### ISSUE THREAD

**Issue by Neobii** [copleykj/socialize-user-model#2]
Since only one object can transform the users collection at a time, it would be nice to use a commonly use package that does the transformation to dodge some package conflicts.  https://github.com/dburles/meteor-collection-helpers

**Comment by copleykj** [comment]
I think this is going to have to be a one or the other. I could try to monkey patch things but I don't see the point.. Each way creates a "Model" but this package just creates it the way the rest of the socialize packages do it.

**Comment by cleor41** [comment]
This is the issue I have right now too. It's kind of a breaker since my whole project uses collection helpers.

**Comment by Neobii** [comment]
Yup, in the new updated meteor docs, they are suggesting to use the
collection helpers package now.
